# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Aplicar Desde México
#tagline:          'A Jekyll theme'
description:      'Reduciendo la asimetría de información'
url:               https://aplicardesdemexico.github.io/
#baseurl:           /

author:
  name:           'aplicardesdemexico@gmail.com'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:
